import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { SignIn, SignInButton, SignOutButton, useUser } from '@clerk/nextjs';

const Home: NextPage = () => {
	const user = useUser();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.container}>
					{!user.isSignedIn && <SignInButton />}
					{!!user.isSignedIn && <SignOutButton />}
				</div>
			</main>
		</>
	);
};

export default Home;
